name: 🐛 Bug Report
description: File a bug report to help us improve EternalCore
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please ensure that you have searched the existing issues to see if this bug has already been reported.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: I was doing X and Y happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Video
      description: If applicable, add screenshots or a video to help explain your problem.

  - type: dropdown
    id: server-software
    attributes:
      label: Server Software
      description: What server software are you using?
      options:
        - Paper
        - Purpur
        - Spigot
        - Folia
        - Other (please specify in logs)
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running? (e.g. 1.20.4)
      placeholder: 1.20.4
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of EternalCore are you running? (Check with /ver EternalCore)
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Please paste any relevant logs or stack traces here. Use a pastebin service if the log is too long.
      render: shell
