name: MC Plugin Compatibility Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-minecraft-versions:
    runs-on: self-hosted
    strategy:
      matrix:
        mc_version: [1.18.2, 1.19.4, 1.20.6, 1.21.7]
    env:
      PLUGIN_GLOB: "eternalcore-plugin/build/libs/EternalCore*.jar"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - run: chmod +x gradlew

      - run: ./gradlew clean eternalcore-plugin:shadowJar

      - id: find-jar
        run: |
          PLUGIN_JAR=$(find ./eternalcore-plugin/build/libs -name 'EternalCore*.jar' | head -n 1)
          echo "PLUGIN_JAR=$PLUGIN_JAR" >> $GITHUB_ENV
          if [ -z "$PLUGIN_JAR" ]; then
            echo "Plugin JAR not found!"
            exit 1
          fi

      - id: get_build_number
        env:
          MC_VERSION: ${{ matrix.mc_version }}
        run: |
          BUILD_NUMBER=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/${MC_VERSION}/builds" | jq '.builds | max_by(.build) | .build')
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - run: |
          mkdir mc-server
          cd mc-server
          echo "Downloading Paper ${{ matrix.mc_version }} build ${{ steps.get_build_number.outputs.build_number }}"
          wget "https://api.papermc.io/v2/projects/paper/versions/${{ matrix.mc_version }}/builds/${{ steps.get_build_number.outputs.build_number }}/downloads/paper-${{ matrix.mc_version }}-${{ steps.get_build_number.outputs.build_number }}.jar" -O paper.jar
          mkdir plugins
          cp ../${{ env.PLUGIN_JAR }} plugins/

      - run: echo "eula=true" > mc-server/eula.txt

      - run: |
          cat > mc-server/server.properties <<EOF
          allow-nether=false
          level-type=FLAT
          max-world-size=16
          EOF

      - run: |
          cat > mc-server/bukkit.yml <<EOF
          settings:
            allow-end: false
          EOF

      - run: |
          cd mc-server
          java -Xmx1G -jar paper.jar nogui > server.log 2>&1 &
          SERVER_PID=$!
          sleep 60
          kill $SERVER_PID
          wait $SERVER_PID || true
          if grep -i -E 'error|exception|failed' server.log; then
            cat server.log
            exit 1
          fi
