name: Run unit tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v3.10.0
        with:
          distribution: adopt
          java-version: '${{ matrix.java }}'
      - name: Cache Gradle
        uses: actions/cache@v3.2.6
        with:
          path: ~/.gradle
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: '${{ runner.os }}-gradle-'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: './gradlew core:test'
